### ISSUE TITLE
QR codes - the App crashes when saving QR code

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o-android#12]
The App crushes when you click on the generated QR code.

**Comment by cyb3rko** [comment]
Interesting, for me it doesn't.
Normally it should then save the image to your gallery.

I will implement Crashlytics in the next update, then I can (hopefully) fix it.

**Comment by cyb3rko** [comment]
Fixed in 6308063496f5107bdf9eb92b4398105754edcfe6
