### ISSUE TITLE
Avatar - The App crashes when saving Avatar

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o-android#13]
The App crushes when you click on the save button.

**Comment by cyb3rko** [comment]
Same as mentioned in #12

**Comment by cyb3rko** [comment]
@asim Do you have the same problem or does it work for you?

**Comment by asim** [comment]
No problem saving the avatar

**Comment by asim** [comment]
Pixel 6

**Comment by lambdaR** [comment]
Playstore says the required android is 4.1 and up and i have tried the app on an old phone (android 8). Try the emulator for android 8 ... I  think there is a saving problem on old android versions

**Comment by cyb3rko** [comment]
@lambdaR  Yeah, the file system heavily changed with Android 10 and 11.
I will try that

**Comment by cyb3rko** [comment]
@asim Alright, good to hear. Thank you
Btw, have you upgraded? :) Last time you said you have Pixel 5

**Comment by asim** [comment]
Yea upgraded. Pixel 5 bricked itself. Battery overheated and died.

**Comment by cyb3rko** [comment]
I could reproduce the error with Android 8.0.
Implemented a fix, will come in the next update.

**Comment by cyb3rko** [comment]
Fixed in 6308063496f5107bdf9eb92b4398105754edcfe6
