### ISSUE TITLE
Add About section

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o-android#15]
Display app current version in the welcome page and also add new item **about** in the kebab menu where you can mention the current version of the app.

**Comment by cyb3rko** [comment]
Good idea showing the version.
The About section will come soon, I have to give credits to licensed icons, animations and libraries as well.

**Comment by cyb3rko** [comment]
PS: I have never heard of the Kebab menu :D
But it seems to exist:

![image](https://user-images.githubusercontent.com/46033730/181821772-3f5150c8-4037-426a-8aa9-62e69ec3ad51.png)

**Comment by cyb3rko** [comment]
The note for the app version is included in #19
